name: check_code_quality
on: pull_request
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/set-up-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install black
      - run: |
          black --check --verbose